version: "3.9"

services:
  keycloak:
    container_name: mattermost-meetup-keycloak
    restart: unless-stopped
    # platform: linux/amd64
    image: quay.io/keycloak/keycloak:22.0.0
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data:rw
    environment:
      - PROXY_ADDRESS_FORWARDING="true"
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command:
      - start-dev
  openldap:
    platform: linux/amd64
    container_name: mattermost-meetup-ldap
    hostname: openldap
    restart: unless-stopped
    image: rroemhild/test-openldap:latest
    ports:
      - "10389:10389"
      - "10636:10636"
  mattermost:
    platform: linux/amd64
    container_name: mattermost-meetup
    depends_on:
      postgres:
        condition: service_healthy
    image: mattermost/mattermost-enterprise-edition:release-8.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    ports:
      - "8065:8065"
      - "8067:8067"
    tmpfs:
      - /tmp
    volumes:
      - ./volumes/mattermost/config:/mattermost/config:rw
      - ./volumes/mattermost/data:/mattermost/data:rw
      - ./volumes/mattermost/logs:/mattermost/logs:rw
      - ./volumes/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/mattermost/client/plugins:/mattermost/client/plugins:rw
      - ./volumes/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
      - ./samlCert.crt:/mattermost/config/samlCert.crt
    environment:
      - MM_SqlSettings_DriverName=postgres
      - MM_SqlSettings_DataSource=postgres://mmuser:mmuser_password@mattermost-meetup-postgres:5432/mattermost?sslmode=disable&connect_timeout=10&binary_parameters=yes
      - MM_ServiceSettings_EnableLocalMode=true
      - MM_ServiceSettings_LocalModeSocketLocation=/var/tmp/mattermost_local.socket
      - MM_ServiceSettings_LicenseFileLocation=/mattermost/config/license.mattermost-enterprise
  postgres:
    container_name: mattermost-meetup-postgres
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
      - LISTEN_ADDRESS="*"
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: false
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U mmuser -d mattermost
      interval: 10s
      timeout: 3s
      retries: 3